apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: neo4j
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: neo4j-neo4j
          servicePort: 7474
        path: /neo4j(/|$)(.*)