---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: authentities-v1
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: authentities-v1
  chart:
    git: https://github.com/guanwei/flux-docker-desktop
    path: charts/micro-service
    ref: master
  values:
    fullnameOverride: authentities-v1
    image:
      repository: registry.cn-shanghai.aliyuncs.com/src-co/authentities-v1
      tag: 1.21.19283.143806
    imagePullSecrets:
      - name: hsc-regsecret
    containerPort: 8196
    env:
      - name: JAVA_OPTS
        value: "-DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector -DAsyncLogger.RingBufferSize=117965"
      - name: JBP_CONFIG_OPEN_JDK_JRE
        value: "[memory_calculator: {memory_sizes: {metaspace: 96m..256m}}]"
      - name: SPRING_PROFILES_ACTIVE
        value: local
      # RabbitMQ Configuration
      - name: COM_PHILIPS_SAPPHIRE_INFRASTRUCTURE_MESSAGING_CONNECTION_HOST
        value: amqp://admin:admin@rabbitmq.default:5672
      - name: COM_PHILIPS_SAPPHIRE_INFRASTRUCTURE_MESSAGING_RABBIT_URI
        value: amqp://admin:admin@rabbitmq.default:5672
      - name: COM_PHILIPS_SAPPHIRE_INFRASTRUCTURE_LOGGING_RABBIT_URI
        value: amqp://admin:admin@rabbitmq.default:5672
      # Redis configuration
      - name: REDIS_AUTH_HOST
        value: redis-master.default
      - name: REDIS_AUTH_PORT
        value: "6379"
      - name: REDIS_AUTH_PASSWORD
        value: admin
      - name: REDIS_HOST
        value: redis-master.default
      - name: REDIS_PORT
        value: "6379"
      - name: REDIS_PASSWORD
        value: admin
      # Neo4j configuration
      - name: NEO4J_SERVER_READ_URI
        value: bolt://neo4j-neo4j-core-0.neo4j-neo4j.default:7687
      - name: NEO4J_SERVER_WRITE_URI
        value: bolt://neo4j-neo4j-core-0.neo4j-neo4j.default:7687
      - name: NEO4J_SERVER_USERNAME
        value: neo4j
      - name: NEO4J_SERVER_PASSWORD
        value: admin
      # Eureka configuration
      - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://eureka.default:8761/eureka
      - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
        value: 'true'
      - name: EUREKA_CLIENT_ENABLED
        value: 'true'
      - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
        value: 'true'
      # MongoDB Configuration
      - name: SPRING_DATA_MONGODB_URI
        value: mongodb://mongodb.default:27017/co?ssl=false
      - name: MONGO_ORGDB_URI
        value: mongodb://mongodb.default:27017/co?ssl=false
