---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: heapster
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: heapster
  chart:
    repository: http://mirror.azure.cn/kubernetes/charts
    name: heapster
    version: 1.0.1
  values:
    command:
      - "/heapster"
      - "--source=kubernetes:https://kubernetes.default?useServiceAccount=true&kubeletHttps=true&kubeletPort=10250&insecure=true"
    service:
      externalPort: 80