---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: rabbitmq-ha
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: rabbitmq-ha
  chart:
    repository: http://mirror.azure.cn/kubernetes/charts
    name: rabbitmq-ha
    version: 1.32.1
  values:
    rabbitmqUsername: guest
    rabbitmqPassword: guest
    managementUsername: admin
    managementPassword: admin
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      path: /rabbitmq(/|$)(.*)