---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: redis
  chart:
    repository: http://mirror.azure.cn/kubernetes/charts/
    name: redis
    version: 9.2.0
  values:
    # cluster:
    #   enabled: false
    password: admin
    metrics:
      enabled: true