---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: sealed-secrets-controller
  chart:
    repository: http://mirror.azure.cn/kubernetes/charts/
    name: sealed-secrets
    version: 1.4.0
  values:
    crd:
      keep: false