---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: sealed-secrets
  chart:
    repository: http://mirror.azure.cn/kubernetes/charts/
    name: sealed-secrets
    version: 1.4.0
    