---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/delete: "true"
spec:
  releaseName: vault
  chart:
    git: https://github.com/hashicorp/vault-helm
    ref: master