{{ if not .Values.config.existingConfigMapName }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eureka.fullname" . }}
  labels:
{{ include "eureka.labels" . | indent 4 }}
data:
  bootstrap.yaml: |
    server:
      port: {{ .Values.service.internalPort }}
    spring:
      application:
        name: eureka-server
      cloud:
        config:
        {{- if .Values.spring.cloud.config.enabled }}
          enabled: {{ .Values.spring.cloud.config.enabled }}
          uri: {{ required "A valid value of spring.cloud.config.uri is required!" .Values.spring.cloud.config.uri }}
        {{- else }}
          enabled: false
        {{- end }}

  application.yaml: |
    eureka:
      instance:
        hostname: localhost
      client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
{{ end }}
