apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "eureka.fullname" . }}
  labels:
{{ include "eureka.labels" . | indent 4 }}
spec:
  replicas:  {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eureka.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "eureka.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: eureka-server
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 20
        volumeMounts:
        - mountPath: /config
          name: eureka-server-config
      volumes:
      - name: eureka-server-config
        configMap:
        {{- if .Values.config.existingConfigMapName }}
          name: {{ .Values.config.existingConfigMapName }}
        {{- else }}
          name: {{ include "eureka.fullname" . }}
        {{- end }}
