apiVersion: v1
kind: Service
metadata:
  name: {{ include "eureka.fullname" . }}
  labels:
{{ include "eureka.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "eureka.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
